[project]
name = "shadow-box-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kellen Galban", email = "kellengalban751@berkeley.edu" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
shadow-box-predictor = "shadow_box_predictor:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
